version: "3.8"

services:
  mysql:
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spring-boot-demo
  redis:
    image: redis:7.0.4-alpine
    ports:
      - "6379:6379"
