server:
  port: 8080
  servlet:
    context-path: /demo
qiniu:
  ## 此处填写你自己的七牛云 access key
  accessKey: xx
  ## 此处填写你自己的七牛云 secret key
  secretKey: xxx
  ## 此处填写你自己的七牛云 bucket
  bucket: blog
  ## 此处填写你自己的七牛云 域名
  prefix: https://static.xkcoding.com/
spring:
  servlet:
    multipart:
      enabled: true
      location: /Users/yangkai.shen/Codes/xkcoding/spring-boot-demo/tmp
      file-size-threshold: 5MB
      max-file-size: 20MB
