version: "3.8"

services:
  mysql:
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spring-boot-demo
    volumes:
      - "./sql/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./sql/data.sql:/docker-entrypoint-initdb.d/2.sql"
    command: --default-authentication-plugin=mysql_native_password
