version: "3.8"

services:
  master:
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spring-boot-demo
    volumes:
      - ./master:/etc/mysql/conf.d
  slave1:
    image: mysql:8.0.30
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spring-boot-demo
    volumes:
      - ./slave1:/etc/mysql/conf.d
  slave2:
    image: mysql:8.0.30
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spring-boot-demo
    volumes:
      - ./slave2:/etc/mysql/conf.d
