version: "3.8"

services:
  mysql:
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spring-boot-demo
  zookeeper:
    image: zookeeper:3.8.0
    ports:
      - "2181:2181"
